// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetRecipeBooks request
	GetRecipeBooks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRecipeBook request with any body
	PostRecipeBookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRecipeBook(ctx context.Context, body PostRecipeBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBook request
	DeleteBook(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBook request
	GetBook(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutBook request with any body
	PutBookWithBody(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutBook(ctx context.Context, bookId string, body PutBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecipes request
	GetRecipes(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostRecipe request with any body
	PostRecipeWithBody(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRecipe(ctx context.Context, bookId string, body PostRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteRecipe request
	DeleteRecipe(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecipe request
	GetRecipe(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutRecipe request with any body
	PutRecipeWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutRecipe(ctx context.Context, bookId string, recipeId string, body PutRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDirectionSteps request
	GetDirectionSteps(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostDirectionStep request with any body
	PostDirectionStepWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostDirectionStep(ctx context.Context, bookId string, recipeId string, body PostDirectionStepJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStep request
	GetStep(ctx context.Context, bookId string, recipeId string, stepId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutStep request with any body
	PutStepWithBody(ctx context.Context, bookId string, recipeId string, stepId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutStep(ctx context.Context, bookId string, recipeId string, stepId string, body PutStepJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIngredients request
	GetIngredients(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIngredient request with any body
	PostIngredientWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostIngredient(ctx context.Context, bookId string, recipeId string, body PostIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteIngredient request
	DeleteIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIngredient request
	GetIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutIngredient request with any body
	PutIngredientWithBody(ctx context.Context, bookId string, recipeId string, ingredientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, body PutIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetRecipeBooks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecipeBooksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecipeBookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecipeBookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecipeBook(ctx context.Context, body PostRecipeBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecipeBookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBook(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBookRequest(c.Server, bookId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetBook(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBookRequest(c.Server, bookId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutBookWithBody(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutBookRequestWithBody(c.Server, bookId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutBook(ctx context.Context, bookId string, body PutBookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutBookRequest(c.Server, bookId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRecipes(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecipesRequest(c.Server, bookId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecipeWithBody(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecipeRequestWithBody(c.Server, bookId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRecipe(ctx context.Context, bookId string, body PostRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRecipeRequest(c.Server, bookId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteRecipe(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRecipeRequest(c.Server, bookId, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRecipe(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecipeRequest(c.Server, bookId, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutRecipeWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutRecipeRequestWithBody(c.Server, bookId, recipeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutRecipe(ctx context.Context, bookId string, recipeId string, body PutRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutRecipeRequest(c.Server, bookId, recipeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDirectionSteps(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDirectionStepsRequest(c.Server, bookId, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDirectionStepWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDirectionStepRequestWithBody(c.Server, bookId, recipeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostDirectionStep(ctx context.Context, bookId string, recipeId string, body PostDirectionStepJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostDirectionStepRequest(c.Server, bookId, recipeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStep(ctx context.Context, bookId string, recipeId string, stepId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStepRequest(c.Server, bookId, recipeId, stepId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutStepWithBody(ctx context.Context, bookId string, recipeId string, stepId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutStepRequestWithBody(c.Server, bookId, recipeId, stepId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutStep(ctx context.Context, bookId string, recipeId string, stepId string, body PutStepJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutStepRequest(c.Server, bookId, recipeId, stepId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIngredients(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIngredientsRequest(c.Server, bookId, recipeId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIngredientWithBody(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIngredientRequestWithBody(c.Server, bookId, recipeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostIngredient(ctx context.Context, bookId string, recipeId string, body PostIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIngredientRequest(c.Server, bookId, recipeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteIngredientRequest(c.Server, bookId, recipeId, ingredientId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIngredientRequest(c.Server, bookId, recipeId, ingredientId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutIngredientWithBody(ctx context.Context, bookId string, recipeId string, ingredientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutIngredientRequestWithBody(c.Server, bookId, recipeId, ingredientId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutIngredient(ctx context.Context, bookId string, recipeId string, ingredientId string, body PutIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutIngredientRequest(c.Server, bookId, recipeId, ingredientId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetRecipeBooksRequest generates requests for GetRecipeBooks
func NewGetRecipeBooksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostRecipeBookRequest calls the generic PostRecipeBook builder with application/json body
func NewPostRecipeBookRequest(server string, body PostRecipeBookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRecipeBookRequestWithBody(server, "application/json", bodyReader)
}

// NewPostRecipeBookRequestWithBody generates requests for PostRecipeBook with any type of body
func NewPostRecipeBookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBookRequest generates requests for DeleteBook
func NewDeleteBookRequest(server string, bookId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBookRequest generates requests for GetBook
func NewGetBookRequest(server string, bookId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutBookRequest calls the generic PutBook builder with application/json body
func NewPutBookRequest(server string, bookId string, body PutBookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutBookRequestWithBody(server, bookId, "application/json", bodyReader)
}

// NewPutBookRequestWithBody generates requests for PutBook with any type of body
func NewPutBookRequestWithBody(server string, bookId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetRecipesRequest generates requests for GetRecipes
func NewGetRecipesRequest(server string, bookId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostRecipeRequest calls the generic PostRecipe builder with application/json body
func NewPostRecipeRequest(server string, bookId string, body PostRecipeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRecipeRequestWithBody(server, bookId, "application/json", bodyReader)
}

// NewPostRecipeRequestWithBody generates requests for PostRecipe with any type of body
func NewPostRecipeRequestWithBody(server string, bookId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRecipeRequest generates requests for DeleteRecipe
func NewDeleteRecipeRequest(server string, bookId string, recipeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRecipeRequest generates requests for GetRecipe
func NewGetRecipeRequest(server string, bookId string, recipeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutRecipeRequest calls the generic PutRecipe builder with application/json body
func NewPutRecipeRequest(server string, bookId string, recipeId string, body PutRecipeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutRecipeRequestWithBody(server, bookId, recipeId, "application/json", bodyReader)
}

// NewPutRecipeRequestWithBody generates requests for PutRecipe with any type of body
func NewPutRecipeRequestWithBody(server string, bookId string, recipeId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDirectionStepsRequest generates requests for GetDirectionSteps
func NewGetDirectionStepsRequest(server string, bookId string, recipeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/direction-steps", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostDirectionStepRequest calls the generic PostDirectionStep builder with application/json body
func NewPostDirectionStepRequest(server string, bookId string, recipeId string, body PostDirectionStepJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostDirectionStepRequestWithBody(server, bookId, recipeId, "application/json", bodyReader)
}

// NewPostDirectionStepRequestWithBody generates requests for PostDirectionStep with any type of body
func NewPostDirectionStepRequestWithBody(server string, bookId string, recipeId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/direction-steps", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetStepRequest generates requests for GetStep
func NewGetStepRequest(server string, bookId string, recipeId string, stepId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "stepId", runtime.ParamLocationPath, stepId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/direction-steps/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutStepRequest calls the generic PutStep builder with application/json body
func NewPutStepRequest(server string, bookId string, recipeId string, stepId string, body PutStepJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutStepRequestWithBody(server, bookId, recipeId, stepId, "application/json", bodyReader)
}

// NewPutStepRequestWithBody generates requests for PutStep with any type of body
func NewPutStepRequestWithBody(server string, bookId string, recipeId string, stepId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "stepId", runtime.ParamLocationPath, stepId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/direction-steps/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetIngredientsRequest generates requests for GetIngredients
func NewGetIngredientsRequest(server string, bookId string, recipeId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/ingredients", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostIngredientRequest calls the generic PostIngredient builder with application/json body
func NewPostIngredientRequest(server string, bookId string, recipeId string, body PostIngredientJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostIngredientRequestWithBody(server, bookId, recipeId, "application/json", bodyReader)
}

// NewPostIngredientRequestWithBody generates requests for PostIngredient with any type of body
func NewPostIngredientRequestWithBody(server string, bookId string, recipeId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/ingredients", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteIngredientRequest generates requests for DeleteIngredient
func NewDeleteIngredientRequest(server string, bookId string, recipeId string, ingredientId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "ingredientId", runtime.ParamLocationPath, ingredientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/ingredients/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIngredientRequest generates requests for GetIngredient
func NewGetIngredientRequest(server string, bookId string, recipeId string, ingredientId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "ingredientId", runtime.ParamLocationPath, ingredientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/ingredients/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutIngredientRequest calls the generic PutIngredient builder with application/json body
func NewPutIngredientRequest(server string, bookId string, recipeId string, ingredientId string, body PutIngredientJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutIngredientRequestWithBody(server, bookId, recipeId, ingredientId, "application/json", bodyReader)
}

// NewPutIngredientRequestWithBody generates requests for PutIngredient with any type of body
func NewPutIngredientRequestWithBody(server string, bookId string, recipeId string, ingredientId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "bookId", runtime.ParamLocationPath, bookId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "recipeId", runtime.ParamLocationPath, recipeId)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "ingredientId", runtime.ParamLocationPath, ingredientId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recipe-books/%s/recipes/%s/ingredients/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetRecipeBooks request
	GetRecipeBooksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRecipeBooksResponse, error)

	// PostRecipeBook request with any body
	PostRecipeBookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecipeBookResponse, error)

	PostRecipeBookWithResponse(ctx context.Context, body PostRecipeBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecipeBookResponse, error)

	// DeleteBook request
	DeleteBookWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*DeleteBookResponse, error)

	// GetBook request
	GetBookWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*GetBookResponse, error)

	// PutBook request with any body
	PutBookWithBodyWithResponse(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutBookResponse, error)

	PutBookWithResponse(ctx context.Context, bookId string, body PutBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PutBookResponse, error)

	// GetRecipes request
	GetRecipesWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*GetRecipesResponse, error)

	// PostRecipe request with any body
	PostRecipeWithBodyWithResponse(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecipeResponse, error)

	PostRecipeWithResponse(ctx context.Context, bookId string, body PostRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecipeResponse, error)

	// DeleteRecipe request
	DeleteRecipeWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*DeleteRecipeResponse, error)

	// GetRecipe request
	GetRecipeWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetRecipeResponse, error)

	// PutRecipe request with any body
	PutRecipeWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutRecipeResponse, error)

	PutRecipeWithResponse(ctx context.Context, bookId string, recipeId string, body PutRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*PutRecipeResponse, error)

	// GetDirectionSteps request
	GetDirectionStepsWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetDirectionStepsResponse, error)

	// PostDirectionStep request with any body
	PostDirectionStepWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDirectionStepResponse, error)

	PostDirectionStepWithResponse(ctx context.Context, bookId string, recipeId string, body PostDirectionStepJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDirectionStepResponse, error)

	// GetStep request
	GetStepWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, reqEditors ...RequestEditorFn) (*GetStepResponse, error)

	// PutStep request with any body
	PutStepWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutStepResponse, error)

	PutStepWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, body PutStepJSONRequestBody, reqEditors ...RequestEditorFn) (*PutStepResponse, error)

	// GetIngredients request
	GetIngredientsWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetIngredientsResponse, error)

	// PostIngredient request with any body
	PostIngredientWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIngredientResponse, error)

	PostIngredientWithResponse(ctx context.Context, bookId string, recipeId string, body PostIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIngredientResponse, error)

	// DeleteIngredient request
	DeleteIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*DeleteIngredientResponse, error)

	// GetIngredient request
	GetIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*GetIngredientResponse, error)

	// PutIngredient request with any body
	PutIngredientWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutIngredientResponse, error)

	PutIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, body PutIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*PutIngredientResponse, error)
}

type GetRecipeBooksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipeBookList
}

// Status returns HTTPResponse.Status
func (r GetRecipeBooksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecipeBooksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostRecipeBookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RecipeBook
}

// Status returns HTTPResponse.Status
func (r PostRecipeBookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRecipeBookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteBookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteBookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetBookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipeBook
}

// Status returns HTTPResponse.Status
func (r GetBookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutBookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipeBook
}

// Status returns HTTPResponse.Status
func (r PutBookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutBookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRecipesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecipeList
}

// Status returns HTTPResponse.Status
func (r GetRecipesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecipesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostRecipeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Recipe
}

// Status returns HTTPResponse.Status
func (r PostRecipeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRecipeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteRecipeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteRecipeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteRecipeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRecipeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetRecipeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecipeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutRecipeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Recipe
}

// Status returns HTTPResponse.Status
func (r PutRecipeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutRecipeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDirectionStepsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DirectionStepList
}

// Status returns HTTPResponse.Status
func (r GetDirectionStepsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDirectionStepsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostDirectionStepResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *DirectionStep
}

// Status returns HTTPResponse.Status
func (r PostDirectionStepResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostDirectionStepResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStepResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DirectionStep
}

// Status returns HTTPResponse.Status
func (r GetStepResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStepResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutStepResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutStepResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutStepResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIngredientsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *IngredientList
}

// Status returns HTTPResponse.Status
func (r GetIngredientsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIngredientsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostIngredientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Ingredient
}

// Status returns HTTPResponse.Status
func (r PostIngredientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostIngredientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteIngredientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteIngredientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteIngredientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIngredientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Ingredient
}

// Status returns HTTPResponse.Status
func (r GetIngredientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIngredientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutIngredientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Ingredient
}

// Status returns HTTPResponse.Status
func (r PutIngredientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutIngredientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetRecipeBooksWithResponse request returning *GetRecipeBooksResponse
func (c *ClientWithResponses) GetRecipeBooksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRecipeBooksResponse, error) {
	rsp, err := c.GetRecipeBooks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecipeBooksResponse(rsp)
}

// PostRecipeBookWithBodyWithResponse request with arbitrary body returning *PostRecipeBookResponse
func (c *ClientWithResponses) PostRecipeBookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecipeBookResponse, error) {
	rsp, err := c.PostRecipeBookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecipeBookResponse(rsp)
}

func (c *ClientWithResponses) PostRecipeBookWithResponse(ctx context.Context, body PostRecipeBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecipeBookResponse, error) {
	rsp, err := c.PostRecipeBook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecipeBookResponse(rsp)
}

// DeleteBookWithResponse request returning *DeleteBookResponse
func (c *ClientWithResponses) DeleteBookWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*DeleteBookResponse, error) {
	rsp, err := c.DeleteBook(ctx, bookId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBookResponse(rsp)
}

// GetBookWithResponse request returning *GetBookResponse
func (c *ClientWithResponses) GetBookWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*GetBookResponse, error) {
	rsp, err := c.GetBook(ctx, bookId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBookResponse(rsp)
}

// PutBookWithBodyWithResponse request with arbitrary body returning *PutBookResponse
func (c *ClientWithResponses) PutBookWithBodyWithResponse(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutBookResponse, error) {
	rsp, err := c.PutBookWithBody(ctx, bookId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutBookResponse(rsp)
}

func (c *ClientWithResponses) PutBookWithResponse(ctx context.Context, bookId string, body PutBookJSONRequestBody, reqEditors ...RequestEditorFn) (*PutBookResponse, error) {
	rsp, err := c.PutBook(ctx, bookId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutBookResponse(rsp)
}

// GetRecipesWithResponse request returning *GetRecipesResponse
func (c *ClientWithResponses) GetRecipesWithResponse(ctx context.Context, bookId string, reqEditors ...RequestEditorFn) (*GetRecipesResponse, error) {
	rsp, err := c.GetRecipes(ctx, bookId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecipesResponse(rsp)
}

// PostRecipeWithBodyWithResponse request with arbitrary body returning *PostRecipeResponse
func (c *ClientWithResponses) PostRecipeWithBodyWithResponse(ctx context.Context, bookId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRecipeResponse, error) {
	rsp, err := c.PostRecipeWithBody(ctx, bookId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecipeResponse(rsp)
}

func (c *ClientWithResponses) PostRecipeWithResponse(ctx context.Context, bookId string, body PostRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRecipeResponse, error) {
	rsp, err := c.PostRecipe(ctx, bookId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRecipeResponse(rsp)
}

// DeleteRecipeWithResponse request returning *DeleteRecipeResponse
func (c *ClientWithResponses) DeleteRecipeWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*DeleteRecipeResponse, error) {
	rsp, err := c.DeleteRecipe(ctx, bookId, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteRecipeResponse(rsp)
}

// GetRecipeWithResponse request returning *GetRecipeResponse
func (c *ClientWithResponses) GetRecipeWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetRecipeResponse, error) {
	rsp, err := c.GetRecipe(ctx, bookId, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecipeResponse(rsp)
}

// PutRecipeWithBodyWithResponse request with arbitrary body returning *PutRecipeResponse
func (c *ClientWithResponses) PutRecipeWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutRecipeResponse, error) {
	rsp, err := c.PutRecipeWithBody(ctx, bookId, recipeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutRecipeResponse(rsp)
}

func (c *ClientWithResponses) PutRecipeWithResponse(ctx context.Context, bookId string, recipeId string, body PutRecipeJSONRequestBody, reqEditors ...RequestEditorFn) (*PutRecipeResponse, error) {
	rsp, err := c.PutRecipe(ctx, bookId, recipeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutRecipeResponse(rsp)
}

// GetDirectionStepsWithResponse request returning *GetDirectionStepsResponse
func (c *ClientWithResponses) GetDirectionStepsWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetDirectionStepsResponse, error) {
	rsp, err := c.GetDirectionSteps(ctx, bookId, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDirectionStepsResponse(rsp)
}

// PostDirectionStepWithBodyWithResponse request with arbitrary body returning *PostDirectionStepResponse
func (c *ClientWithResponses) PostDirectionStepWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostDirectionStepResponse, error) {
	rsp, err := c.PostDirectionStepWithBody(ctx, bookId, recipeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDirectionStepResponse(rsp)
}

func (c *ClientWithResponses) PostDirectionStepWithResponse(ctx context.Context, bookId string, recipeId string, body PostDirectionStepJSONRequestBody, reqEditors ...RequestEditorFn) (*PostDirectionStepResponse, error) {
	rsp, err := c.PostDirectionStep(ctx, bookId, recipeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostDirectionStepResponse(rsp)
}

// GetStepWithResponse request returning *GetStepResponse
func (c *ClientWithResponses) GetStepWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, reqEditors ...RequestEditorFn) (*GetStepResponse, error) {
	rsp, err := c.GetStep(ctx, bookId, recipeId, stepId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStepResponse(rsp)
}

// PutStepWithBodyWithResponse request with arbitrary body returning *PutStepResponse
func (c *ClientWithResponses) PutStepWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutStepResponse, error) {
	rsp, err := c.PutStepWithBody(ctx, bookId, recipeId, stepId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutStepResponse(rsp)
}

func (c *ClientWithResponses) PutStepWithResponse(ctx context.Context, bookId string, recipeId string, stepId string, body PutStepJSONRequestBody, reqEditors ...RequestEditorFn) (*PutStepResponse, error) {
	rsp, err := c.PutStep(ctx, bookId, recipeId, stepId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutStepResponse(rsp)
}

// GetIngredientsWithResponse request returning *GetIngredientsResponse
func (c *ClientWithResponses) GetIngredientsWithResponse(ctx context.Context, bookId string, recipeId string, reqEditors ...RequestEditorFn) (*GetIngredientsResponse, error) {
	rsp, err := c.GetIngredients(ctx, bookId, recipeId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIngredientsResponse(rsp)
}

// PostIngredientWithBodyWithResponse request with arbitrary body returning *PostIngredientResponse
func (c *ClientWithResponses) PostIngredientWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIngredientResponse, error) {
	rsp, err := c.PostIngredientWithBody(ctx, bookId, recipeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIngredientResponse(rsp)
}

func (c *ClientWithResponses) PostIngredientWithResponse(ctx context.Context, bookId string, recipeId string, body PostIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIngredientResponse, error) {
	rsp, err := c.PostIngredient(ctx, bookId, recipeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIngredientResponse(rsp)
}

// DeleteIngredientWithResponse request returning *DeleteIngredientResponse
func (c *ClientWithResponses) DeleteIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*DeleteIngredientResponse, error) {
	rsp, err := c.DeleteIngredient(ctx, bookId, recipeId, ingredientId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteIngredientResponse(rsp)
}

// GetIngredientWithResponse request returning *GetIngredientResponse
func (c *ClientWithResponses) GetIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, reqEditors ...RequestEditorFn) (*GetIngredientResponse, error) {
	rsp, err := c.GetIngredient(ctx, bookId, recipeId, ingredientId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIngredientResponse(rsp)
}

// PutIngredientWithBodyWithResponse request with arbitrary body returning *PutIngredientResponse
func (c *ClientWithResponses) PutIngredientWithBodyWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutIngredientResponse, error) {
	rsp, err := c.PutIngredientWithBody(ctx, bookId, recipeId, ingredientId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutIngredientResponse(rsp)
}

func (c *ClientWithResponses) PutIngredientWithResponse(ctx context.Context, bookId string, recipeId string, ingredientId string, body PutIngredientJSONRequestBody, reqEditors ...RequestEditorFn) (*PutIngredientResponse, error) {
	rsp, err := c.PutIngredient(ctx, bookId, recipeId, ingredientId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutIngredientResponse(rsp)
}

// ParseGetRecipeBooksResponse parses an HTTP response from a GetRecipeBooksWithResponse call
func ParseGetRecipeBooksResponse(rsp *http.Response) (*GetRecipeBooksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecipeBooksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipeBookList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostRecipeBookResponse parses an HTTP response from a PostRecipeBookWithResponse call
func ParsePostRecipeBookResponse(rsp *http.Response) (*PostRecipeBookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRecipeBookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RecipeBook
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteBookResponse parses an HTTP response from a DeleteBookWithResponse call
func ParseDeleteBookResponse(rsp *http.Response) (*DeleteBookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetBookResponse parses an HTTP response from a GetBookWithResponse call
func ParseGetBookResponse(rsp *http.Response) (*GetBookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipeBook
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutBookResponse parses an HTTP response from a PutBookWithResponse call
func ParsePutBookResponse(rsp *http.Response) (*PutBookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutBookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipeBook
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRecipesResponse parses an HTTP response from a GetRecipesWithResponse call
func ParseGetRecipesResponse(rsp *http.Response) (*GetRecipesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecipesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecipeList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostRecipeResponse parses an HTTP response from a PostRecipeWithResponse call
func ParsePostRecipeResponse(rsp *http.Response) (*PostRecipeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRecipeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Recipe
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteRecipeResponse parses an HTTP response from a DeleteRecipeWithResponse call
func ParseDeleteRecipeResponse(rsp *http.Response) (*DeleteRecipeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteRecipeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetRecipeResponse parses an HTTP response from a GetRecipeWithResponse call
func ParseGetRecipeResponse(rsp *http.Response) (*GetRecipeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecipeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutRecipeResponse parses an HTTP response from a PutRecipeWithResponse call
func ParsePutRecipeResponse(rsp *http.Response) (*PutRecipeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutRecipeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Recipe
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetDirectionStepsResponse parses an HTTP response from a GetDirectionStepsWithResponse call
func ParseGetDirectionStepsResponse(rsp *http.Response) (*GetDirectionStepsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDirectionStepsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DirectionStepList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostDirectionStepResponse parses an HTTP response from a PostDirectionStepWithResponse call
func ParsePostDirectionStepResponse(rsp *http.Response) (*PostDirectionStepResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostDirectionStepResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest DirectionStep
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetStepResponse parses an HTTP response from a GetStepWithResponse call
func ParseGetStepResponse(rsp *http.Response) (*GetStepResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStepResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DirectionStep
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutStepResponse parses an HTTP response from a PutStepWithResponse call
func ParsePutStepResponse(rsp *http.Response) (*PutStepResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutStepResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetIngredientsResponse parses an HTTP response from a GetIngredientsWithResponse call
func ParseGetIngredientsResponse(rsp *http.Response) (*GetIngredientsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIngredientsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IngredientList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostIngredientResponse parses an HTTP response from a PostIngredientWithResponse call
func ParsePostIngredientResponse(rsp *http.Response) (*PostIngredientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostIngredientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Ingredient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseDeleteIngredientResponse parses an HTTP response from a DeleteIngredientWithResponse call
func ParseDeleteIngredientResponse(rsp *http.Response) (*DeleteIngredientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteIngredientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetIngredientResponse parses an HTTP response from a GetIngredientWithResponse call
func ParseGetIngredientResponse(rsp *http.Response) (*GetIngredientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIngredientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ingredient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutIngredientResponse parses an HTTP response from a PutIngredientWithResponse call
func ParsePutIngredientResponse(rsp *http.Response) (*PutIngredientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutIngredientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Ingredient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
