CREATE DATABASE foorester;

\c foorester;

CREATE SCHEMA cook;

CREATE USER cook WITH PASSWORD 'cook';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cook TO cook;
GRANT USAGE ON SCHEMA cook TO cook;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
