// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          pgtype.UUID
	Name        string
	Description string
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Ingredient struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RecipeID    pgtype.UUID
	Qty         string
	Unit        string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Recipe struct {
	ID          pgtype.UUID
	Name        string
	Description string
	BookID      pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Step struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RecipeID    pgtype.UUID
	Duration    string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
