http:
  api:
    server:
      host: localhost
      port: 8080

db:
  pg:
    host: "localhost"
    port: 5432
    database: "foorester"
    schema: "cook"
    ssl: false
    user: "cook"
    pass: "cook"
    max-retries: 5

  nats:
    host: "localhost"
    port: 4222

  logging:
    level: "debug"
