// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package openapi

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Book defines model for Book.
type Book struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// BookList defines model for BookList.
type BookList = []Book

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Id       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Quantity *string `json:"quantity,omitempty"`
}

// IngredientList defines model for IngredientList.
type IngredientList = []Ingredient

// Recipe defines model for Recipe.
type Recipe struct {
	DirectionSteps *[]Step       `json:"directionSteps,omitempty"`
	Id             *string       `json:"id,omitempty"`
	Ingredients    *[]Ingredient `json:"ingredients,omitempty"`
	Name           *string       `json:"name,omitempty"`
}

// RecipeList defines model for RecipeList.
type RecipeList = []Recipe

// Step defines model for Step.
type Step struct {
	Id   *string `json:"id,omitempty"`
	Step *string `json:"step,omitempty"`
}

// StepList defines model for StepList.
type StepList = []Step

// PostBookJSONRequestBody defines body for PostBook for application/json ContentType.
type PostBookJSONRequestBody = Book

// PutBookJSONRequestBody defines body for PutBook for application/json ContentType.
type PutBookJSONRequestBody = Book

// PostRecipeJSONRequestBody defines body for PostRecipe for application/json ContentType.
type PostRecipeJSONRequestBody = Recipe

// PutRecipeJSONRequestBody defines body for PutRecipe for application/json ContentType.
type PutRecipeJSONRequestBody = Recipe

// PostIngredientJSONRequestBody defines body for PostIngredient for application/json ContentType.
type PostIngredientJSONRequestBody = Ingredient

// PutIngredientJSONRequestBody defines body for PutIngredient for application/json ContentType.
type PutIngredientJSONRequestBody = Ingredient

// PostStepJSONRequestBody defines body for PostStep for application/json ContentType.
type PostStepJSONRequestBody = Step

// PutStepJSONRequestBody defines body for PutStep for application/json ContentType.
type PutStepJSONRequestBody = Step
