// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package pg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          pgtype.UUID
	Name        string
	Description string
	OwnerID     pgtype.UUID
}

type Ingredient struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RecipeID    pgtype.UUID
	Qty         string
	Unit        string
}

type Recipe struct {
	ID          pgtype.UUID
	Name        string
	Description string
	BookID      pgtype.UUID
}

type Step struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RecipeID    pgtype.UUID
	Duration    string
}

type User struct {
	ID       pgtype.UUID
	Username string
	Name     string
	Email    string
	Password string
}
